# work flow name
name: Publish Docker Image
# when to trage this work flow
on:
  push:
    branches:
      - "master"
# setup default working dir
defaults:
  run:
    shell: bash
    working-directory: ./App
# the jobs to run this ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #pull all branch and tag data
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to github package
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: frank-datareachable/dockertest/react-nginx
          tag_with_ref: true
