# work flow name
name: Publish Docker Image
# when to trage this work flow
on:
  push:
    branches:
      - "master"
# setup default working dir
defaults:
  run:
    shell: bash
    working-directory: ./App
# the jobs to run this ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # pull all branch and tag data
      - name: Check out the repo
        uses: actions/checkout@v2
      # push the docker to github package
      - name: Push to github package
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          repository: frank-datareachable/dockertest/react-nginx
          dockerfile: Dockerfile.ci
