# work flow name
name: TestWrokFlow
# when to trage this work flow
on:
  push:
    branches:
      - "master"
# setup default working dir
defaults:
  run:
    shell: bash
    working-directory: ./App
# the jobs to run this ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pwd
        run: pwd
      - name: change working directory
        run: ls
      - name: after cd ls
        run: ls
