# work flow name
name: TestWrokFlow
# when to trage this work flow
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

# the jobs to run this ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo "hello world"
        run: echo "hello world"
